services:
  hubproxy:
    image: ghcr.io/kaerti/hubproxy
    container_name: hubproxy
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./src/config.toml:/root/config.toml
    logging:
      driver: json-file
      options:
        max-size: "1g"
        max-file: "2"
